import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LayoutWrapper } from "@/components/layout-wrapper";
import "./globals.css";
import { Providers } from "@/providers";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_PRODUCT_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ scrollBehavior: "smooth" }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <LayoutWrapper>
            {children}
            <Toaster
              closeButton
              toastOptions={{
                className: "bg-slate-400",
                classNames: {
                  title: "!text-white !font-bold !text-md",
                  icon: "!mr-2 !text-2xl",
                  description: "!text-white !text-sm",
                  closeButton: "!text-white",
                  error: "!bg-red-400",
                  success: "!text-green-400",
                  warning: "!text-yellow-400",
                  info: "!bg-blue-400",
                },
              }}
            />
          </LayoutWrapper>
        </Providers>
      </body>
    </html>
  );
}
